CREATE TABLE file (
  file_id SERIAL PRIMARY KEY,
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  public BOOLEAN NOT NULL DEFAULT false,

  user_id VARCHAR(100) NOT NULL,

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);