// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	FileID    int32
	FileName  string
	FileUrl   string
	Public    bool
	UserID    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
